apiVersion: v1
kind: ConfigMap
metadata:
  name: cl3-mqsc
data:
  cl.mqsc: |
    DEFINE CHANNEL(TLSTHREE) CHLTYPE(SVRCONN) SSLCIPH(TLS_RSA_WITH_AES_128_CBC_SHA256) CERTLABL('label1') SSLCAUTH (OPTIONAL) REPLACE
    SET CHLAUTH(TLSTHREE) TYPE(BLOCKUSER) USERLIST(nobody)
    SET CHLAUTH(TLSTHREE) TYPE (ADDRESSMAP) ADDRESS(*) MCAUSER('mqm')
    DEFINE CHANNEL(CL.THREE.CONN) CHLTYPE(SVRCONN) REPLACE
    SET CHLAUTH(CL.THREE.CONN) TYPE(BLOCKUSER) USERLIST(nobody)
    SET CHLAUTH(CL.THREE.CONN) TYPE (ADDRESSMAP) ADDRESS(*) MCAUSER('mqm')
    ALTER AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHTYPE(IDPWOS) CHCKCLNT(NONE) ADOPTCTX(NO)
    REFRESH SECURITY TYPE(CONNAUTH)
    DEFINE CHANNEL(TO.CL3) CHLTYPE(CLUSRCVR) TRPTYPE(TCP) CONNAME('mqcl3-ibm-mq.mq.svc(1414)') CLUSTER(OCPCL)
    DEFINE CHANNEL(TO.CL1) CHLTYPE(CLUSSDR) TRPTYPE(TCP) CONNAME('mqcl1-ibm-mq.mq.svc(1414)') CLUSTER(OCPCL)
    DEFINE CHANNEL(TO.CL2) CHLTYPE(CLUSSDR) TRPTYPE(TCP) CONNAME('mqcl2-ibm-mq.mq.svc(1414)') CLUSTER(OCPCL)
    DEFINE QLOCAL(IVT.Q) DEFPSIST(YES) MAXDEPTH(5000000) REPLACE
    DEFINE QALIAS(STL1) TARGET(REQQ) CLUSTER(OCPCL) CLWLPRTY(8) REPLACE
    DEFINE QALIAS(CLNQ) TARGET(REQQ) CLUSTER(OCPCL) CLWLPRTY(4) REPLACE
    DEFINE QLOCAL(REQQ) CLUSTER(OCPCL) DEFPSIST(YES) REPLACE
    
